server:
  port: 8087
  servlet:
    context-path: /wuan_news

spring:
  application:
    name: wuan_news_server
  datasource:
    url: jdbc:mysql://130.162.148.198:3306/wuan_news?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: wuan_news
    password: Jwk4MYM7kyiJJr6H
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 下面的配置是给 Springfox 用的，Springfox 使用的路径匹配是基于 AntPathMatcher 的，而 Spring Boot 2.6.X 使用的是 PathPatternMatcher。
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: com.wuan.wuan_news.wuan_news_server.model
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# The jwt.secret has to be very long
jwt:
  secret: ThisIsASecretKeyWhichIsAtLeast64CharactersLongForHS512Algorithm*
  expiration: 86400000